services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: household-backend:latest
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: household-frontend:latest
    depends_on:
      - backend
    ports:
      - "5173:5173"